# Самостоятельная работа 05.12.2020

## numpy

### Задача 0.1

Напишите следующую функцию:

На вход функции приходит матрица из булевых значения (`True` / `False`). Верните `True`, если в каждом столбце есть хотя бы одна `True`.

In [2]:
def columnwise_any_then_all(matrix):
    n = len(matrix)
    if n == 0:
        return True
    m = len(matrix[0])
    if m == 0:
        return True
    for i in range(m):
        used = False
        for j in range(n):
            if matrix[j][i] == True:
                used = True
    if used == False:
        return False
    return True

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

### Задача 0.2

Напишите функцию, которая вернет индекс первого элемента, который больше нуля. Предполагайте, что положительный элемент всегда существует.

In [11]:
def where_the_first_positive(array):
    for i in range(len(array)):
        if array[i] > 0:
            return i

### Задача 0.3
На вход функции приходит np.array в котором лежат целые числа. Число означает изменение температуры в этот день по сравнению со вчерашним днем. Верните количество дней, когда температура была больше `target`.
Стартовая температура равна 10 градусам.

In [10]:
def warming(temperature_deltas, target):
    temp = 10
    cnt = 0
    for d in temperature_deltas :
        temp = temp + d
        if temp > target:
            cnt = cnt + 1
    return cnt

## pandas

В этой секции будем работать с датасетом, где представлена информация о держателях банковских карт. 

В данной секции нельзя глазами отсмотреть весь датасет и напечатать ответ на вопрос. Решения задач должны работать с любой подвыборкой и оставаться корректными.

In [2]:
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
df = pd.read_csv('credit_card_users.csv')

### Задача 1.0
Выведете первые 10 строчек в датасете.

In [4]:
print(df.head(11))

    CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0   768805383  Existing Customer            45      M                3
1   818770008  Existing Customer            49      F                5
2   713982108  Existing Customer            51      M                3
3   769911858  Existing Customer            40      F                4
4   709106358  Existing Customer            40      M                3
5   713061558  Existing Customer            44      M                2
6   810347208  Existing Customer            51      M                4
7   818906208  Existing Customer            32      M                0
8   710930508  Existing Customer            37      M                3
9   719661558  Existing Customer            48      M                2
10  708790833  Existing Customer            42      M                5

   Education_Level Marital_Status Income_Category Card_Category  \
0      High School        Married     $60K - $80K          Blue
1         Graduate         Single  Less than $40K          Blue
2         Graduate        Married    $80K - $120K          Blue
3      High School        Unknown  Less than $40K          Blue
4       Uneducated        Married     $60K - $80K          Blue
5         Graduate        Married     $40K - $60K          Blue
6          Unknown        Married         $120K +          Gold
7      High School        Unknown     $60K - $80K        Silver
8       Uneducated         Single     $60K - $80K          Blue
9         Graduate         Single    $80K - $120K          Blue
10      Uneducated        Unknown         $120K +          Blue

    Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0               39  ...       12691.0                  777          11914.0
1               44  ...        8256.0                  864           7392.0
2               36  ...        3418.0                    0           3418.0
3               34  ...        3313.0                 2517            796.0
4               21  ...        4716.0                    0           4716.0
5               36  ...        4010.0                 1247           2763.0
6               46  ...       34516.0                 2264          32252.0
7               27  ...       29081.0                 1396          27685.0
8               36  ...       22352.0                 2517          19835.0
9               36  ...       11656.0                 1677           9979.0
10              31  ...        6748.0                 1467           5281.0

    Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0                  1.335             1144              42
1                  1.541             1291              33
2                  2.594             1887              20
3                  1.405             1171              20
4                  2.175              816              28
5                  1.376             1088              24
6                  1.975             1330              31
7                  2.204             1538              36
8                  3.355             1350              24
9                  1.524             1441              32
10                 0.831             1201              42

    Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                 1.625                  0.061
1                 3.714                  0.105
2                 2.333                  0.000
3                 2.333                  0.760
4                 2.500                  0.000
5                 0.846                  0.311
6                 0.722                  0.066
7                 0.714                  0.048
8                 1.182                  0.113
9                 0.882                  0.144
10                0.680                  0.217

    Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                            0.000093
1                                            0.000057
2                                            0.000021
3                                            0.000134
4                                            0.000022
5                                            0.000055
6                                            0.000123
7                                            0.000086
8                                            0.000045
9                                            0.000303
10                                           0.000191

    Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0                                             0.99991
1                                             0.99994
2                                             0.99998
3                                             0.99987
4                                             0.99998
5                                             0.99994
6                                             0.99988
7                                             0.99991
8                                             0.99996
9                                             0.99970
10                                            0.99981

[11 rows x 23 columns]

### Задача 1.1

Напиишите код, который поместит в переменную `ans` список из уникальных типов карт, которые представлены в датасете? Колонка: `Card_Category`

In [7]:
ans = df['Card_Category'].unique()
print(ans)

['Blue' 'Gold' 'Silver' 'Platinum']

### Задача 1.2

Какие максимальные и минимальные лимитные кредиты имеют держатели?
В переменную `max_lim` поместите максимальный лимит, в переменную `min_lim` - минимальный.

In [9]:
min_lim = df['Credit_Limit'].min()
max_lim = df['Credit_Limit'].max()
#print(max_lim)
#print(min_lim)

34516.0
1438.3

### Задача 1.3

Какие максимальные и минимальные лимитные кредиты (`Credit_Limit`) имеют держатели с разными премиальных категориях (`Card_Category`)?

Поместите pd.Series с минимальными лимитами в переменную `min_lim`, а максимальные в переменную `max_lim`.

### Задача 1.4
Постройте диаграмму рассеяния, где по оси `x` будет возраст человека, а по `y` его кредитный лимит.

Одной-двумя фразами опишите, как будет изменяться кредитный лимит при изменении возраста.

In [ ]:
df.plot( x='Customer_Age', y='Credit_Limit', kind='hist')

### Задача 1.5

Интересно узнать, как связаны уровни образования и кредитный лимит. Нарисуйте график, где по оси `x` уровни образования, а по `y` средний кредитный лимит в группе.

Какой вывод можно сделать? Как связаны уровень образования и лимит?

### Задача 1.6


Отношение к кредитам может сильно различаться в зависимости от доходов.

Предварительно почистите выборку от тех, кто вообще не пользуется кредитной картой.
Далее постройте такую величину: среднее использование кредитной карты (`Avg_Utilization_Ratio`) в зависимости от `Income_Category`. Внутри каждой категории доходов необходимо усреднить `Avg_Utilization_Ratio`.